# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\"H\n\rEncodeRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x18\n\x0bprompt_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_prompt_name\":\n\x0e\x45ncodeResponse\x12(\n\nembeddings\x18\x01 \x03(\x0b\x32\x14.embedding.Embedding\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\"v\n\x11SimilarityRequest\x12.\n\x10query_embeddings\x18\x01 \x03(\x0b\x32\x14.embedding.Embedding\x12\x31\n\x13\x64ocument_embeddings\x18\x02 \x03(\x0b\x32\x14.embedding.Embedding\"V\n\x12SimilarityResponse\x12\x14\n\x0csimilarities\x18\x01 \x03(\x02\x12\x13\n\x0bnum_queries\x18\x02 \x01(\x05\x12\x15\n\rnum_documents\x18\x03 \x01(\x05\"\x14\n\x12HealthCheckRequest\":\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x12\n\nmodel_name\x18\x02 \x01(\t2\xf1\x01\n\x10\x45mbeddingService\x12=\n\x06\x45ncode\x12\x18.embedding.EncodeRequest\x1a\x19.embedding.EncodeResponse\x12P\n\x11\x43omputeSimilarity\x12\x1c.embedding.SimilarityRequest\x1a\x1d.embedding.SimilarityResponse\x12L\n\x0bHealthCheck\x12\x1d.embedding.HealthCheckRequest\x1a\x1e.embedding.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODEREQUEST']._serialized_start=30
  _globals['_ENCODEREQUEST']._serialized_end=102
  _globals['_ENCODERESPONSE']._serialized_start=104
  _globals['_ENCODERESPONSE']._serialized_end=162
  _globals['_EMBEDDING']._serialized_start=164
  _globals['_EMBEDDING']._serialized_end=191
  _globals['_SIMILARITYREQUEST']._serialized_start=193
  _globals['_SIMILARITYREQUEST']._serialized_end=311
  _globals['_SIMILARITYRESPONSE']._serialized_start=313
  _globals['_SIMILARITYRESPONSE']._serialized_end=399
  _globals['_HEALTHCHECKREQUEST']._serialized_start=401
  _globals['_HEALTHCHECKREQUEST']._serialized_end=421
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=423
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=481
  _globals['_EMBEDDINGSERVICE']._serialized_start=484
  _globals['_EMBEDDINGSERVICE']._serialized_end=725
# @@protoc_insertion_point(module_scope)
