# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\"H\n\rEncodeRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x18\n\x0bprompt_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_prompt_name\":\n\x0e\x45ncodeResponse\x12(\n\nembeddings\x18\x01 \x03(\x0b\x32\x14.embedding.Embedding\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\"v\n\x11SimilarityRequest\x12.\n\x10query_embeddings\x18\x01 \x03(\x0b\x32\x14.embedding.Embedding\x12\x31\n\x13\x64ocument_embeddings\x18\x02 \x03(\x0b\x32\x14.embedding.Embedding\"V\n\x12SimilarityResponse\x12\x14\n\x0csimilarities\x18\x01 \x03(\x02\x12\x13\n\x0bnum_queries\x18\x02 \x01(\x05\x12\x15\n\rnum_documents\x18\x03 \x01(\x05\"\x14\n\x12HealthCheckRequest\":\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x12\n\nmodel_name\x18\x02 \x01(\t\"\x1d\n\rInjestRequest\x12\x0c\n\x04wiki\x18\x01 \x01(\t\"+\n\x0eInjestResponse\x12\x19\n\x11records_processed\x18\x01 \x01(\x03\";\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0c\n\x04wiki\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x03\"B\n\x10SearchResultItem\x12\r\n\x05score\x18\x01 \x01(\x02\x12\x0b\n\x03qid\x18\x02 \x01(\r\x12\x12\n\npage_title\x18\x03 \x01(\t\">\n\x0eSearchResponse\x12,\n\x07results\x18\x01 \x03(\x0b\x32\x1b.embedding.SearchResultItem2\xef\x02\n\x10\x45mbeddingService\x12=\n\x06\x45ncode\x12\x18.embedding.EncodeRequest\x1a\x19.embedding.EncodeResponse\x12P\n\x11\x43omputeSimilarity\x12\x1c.embedding.SimilarityRequest\x1a\x1d.embedding.SimilarityResponse\x12L\n\x0bHealthCheck\x12\x1d.embedding.HealthCheckRequest\x1a\x1e.embedding.HealthCheckResponse\x12=\n\x06Injest\x12\x18.embedding.InjestRequest\x1a\x19.embedding.InjestResponse\x12=\n\x06Search\x12\x18.embedding.SearchRequest\x1a\x19.embedding.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODEREQUEST']._serialized_start=30
  _globals['_ENCODEREQUEST']._serialized_end=102
  _globals['_ENCODERESPONSE']._serialized_start=104
  _globals['_ENCODERESPONSE']._serialized_end=162
  _globals['_EMBEDDING']._serialized_start=164
  _globals['_EMBEDDING']._serialized_end=191
  _globals['_SIMILARITYREQUEST']._serialized_start=193
  _globals['_SIMILARITYREQUEST']._serialized_end=311
  _globals['_SIMILARITYRESPONSE']._serialized_start=313
  _globals['_SIMILARITYRESPONSE']._serialized_end=399
  _globals['_HEALTHCHECKREQUEST']._serialized_start=401
  _globals['_HEALTHCHECKREQUEST']._serialized_end=421
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=423
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=481
  _globals['_INJESTREQUEST']._serialized_start=483
  _globals['_INJESTREQUEST']._serialized_end=512
  _globals['_INJESTRESPONSE']._serialized_start=514
  _globals['_INJESTRESPONSE']._serialized_end=557
  _globals['_SEARCHREQUEST']._serialized_start=559
  _globals['_SEARCHREQUEST']._serialized_end=618
  _globals['_SEARCHRESULTITEM']._serialized_start=620
  _globals['_SEARCHRESULTITEM']._serialized_end=686
  _globals['_SEARCHRESPONSE']._serialized_start=688
  _globals['_SEARCHRESPONSE']._serialized_end=750
  _globals['_EMBEDDINGSERVICE']._serialized_start=753
  _globals['_EMBEDDINGSERVICE']._serialized_end=1120
# @@protoc_insertion_point(module_scope)
