[workspace]
resolver = "2"
members = [
  "topictrend_core",
  "topictrend_cli",
  "topictrend_web",
  "topictrend_taxonomy",
]

[workspace.dependencies]
parquet = "57"
parquet_derive = "57.0"
dotenv = "0.15"
polars = { version = "0.53", features = [
  "lazy",
  "parquet",
  "strings",
] }
roaring = { version = "0.11", features = [] }
anyhow = "1.0"
ahash = "0.8"
clap = { version = "4", features = ["derive"] }
rayon = "1.11"
chrono = "0.4"
byteorder = "1.5"

[profile.dev]
# Faster compile times, slightly slower runtime
opt-level = 0
debug = 1  # line tables only (not full debug)
incremental = true



