[package]
name = "topictrend_core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "topictrend"


[dependencies]
parquet = { workspace = true }
parquet_derive = { workspace = true }
polars = { workspace = true }
roaring = { workspace = true }
anyhow = { workspace = true }
ahash = { workspace = true }
chrono = { workspace = true }
byteorder = { workspace = true }
