# -*- coding: utf-8 -*-
"""Kazakh wiki analysis - raw

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MaMrNBoxW1eFpOVtAV7MLUdxvyKLPGeo
"""

!uv pip install grpcio grpcio-tools pandas matplotlib

"""# Setup gRPC client for the TopicTrends server"""

!uv run python -m grpc_tools.protoc -I./proto --python_out=. --grpc_python_out=. ./proto/topictrend.proto

import grpc
from grpc import StatusCode
import logging
import topictrend_pb2
import topictrend_pb2_grpc
from datetime import datetime, timedelta

channel_options = [
    ('grpc.keepalive_time_ms', 30000),
    ('grpc.keepalive_timeout_ms', 5000),
    ('grpc.keepalive_permit_without_calls', True),
    ('grpc.http2.max_pings_without_data', 0),
    ('grpc.http2.min_time_between_pings_ms', 10000),
]

class TopicTrendClient:
  def __init__(self, host='localhost', port=50051):
    self.channel = grpc.insecure_channel(f'{host}:{port}', options=channel_options)
    self.stub = topictrend_pb2_grpc.TopicTrendServiceStub(self.channel)
    self.logger = logging.getLogger(__name__)
  def close(self):
    self.channel.close()

  def __enter__(self):
    return self

  def __exit__(self, exc_type, exc_val, exc_tb):
    self.close()

  def _handle_grpc_error(self, e: grpc.RpcError):
    """Handle common gRPC errors"""
    error_mapping = {
        StatusCode.NOT_FOUND: "Resource not found",
        StatusCode.INVALID_ARGUMENT: "Invalid request parameters",
        StatusCode.INTERNAL: "Internal server error",
        StatusCode.UNAVAILABLE: "Service unavailable",
        StatusCode.DEADLINE_EXCEEDED: "Request timeout",
    }

    error_msg = error_mapping.get(e.code(), f"Unknown error: {e.details()}")
    self.logger.error(f"gRPC Error [{e.code()}]: {error_msg}")
    raise Exception(f"gRPC Error: {error_msg}")

"""# Some utility functions to use later
We may need to move all this to a python files to reuse across notebooks
"""

def get_title_by_qid(client, qid, wiki="enwiki"):
    request = topictrend_pb2.TitleByQidRequest(wiki=wiki,qid=qid)
    try:
      response = client.stub.GetTitleByQid(request)
      return response.title
    except grpc.RpcError as e:
        if e.code() == StatusCode.NOT_FOUND:
            # print(f"Warning: Category QID {qid} not found for wiki {wiki}. Returning None.") # Optional: print warning
            return None # Return None if resource not found
        else:
            client._handle_grpc_error(e) # Re-raise for other types of errors


def plot_page_views(views, label):
    """
    Args:
    views: array of objects with date, views keys. date is x axis, views is y axis
    """

    # 1. Extract data into a list of dictionaries
    data = []
    for view in response.views:
        data.append({
            'Date': view.date,
            'Views': view.views
        })

    # 2. Create a Pandas DataFrame
    df = pd.DataFrame(data)

    # 3. Convert the 'Date' column to datetime objects
    df['Date'] = pd.to_datetime(df['Date'])

    # 4. Set the 'Date' column as the index for time-series plotting
    df.set_index('Date', inplace=True)

    # 5. Create the plot
    plt.figure(figsize=(12, 6))
    df['Views'].plot(
        kind='line',
        marker='o',
        markersize=4,
        linestyle='-',
        color='#3498db', # A blue color
        linewidth=2
    )

    # 6. Add labels and a title
    plt.title(f'Daily Views for : {label}', fontsize=16, pad=15)
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Daily Views', fontsize=12)

    # 7. Improve readability of the X-axis and add grid
    plt.xticks(rotation=45)
    plt.ticklabel_format(style='plain', axis='y') # Prevent scientific notation on y-axis
    plt.grid(axis='y', linestyle=':', alpha=0.6)
    plt.tight_layout()

    # 8. Display the plot
    plt.show()


    return df # Optionally return the DataFrame for further analysis

def get_total_page_views_for_category(client,category_qid, wiki, start_date, end_date, depth=20):
  request = topictrend_pb2.CategoryViewsRequest(
      wiki=wiki,
      category_qid=category_qid,
      start_date=start_date,
      end_date=end_date,
      depth=depth,
  )

  try:
      response = client.stub.GetCategoryViews(request)
      # print(f"Category: {response.title} (Q{response.qid})")
      # print(f"Views data: {len(response.views)} days")
      # print(f"Top articles: {len(response.top_articles)}")
      total = 0
      for daily_views in response.views:

          total += daily_views.views
      return total
  except grpc.RpcError as e:
      print(f"RPC failed: {e.code()}, {e.details()}")

# get_total_page_views_for_category(client, 1458083, "enwiki", "2025-11-01", "2025-11-30")

"""# Establish Baseline - Impact Data"""

client = TopicTrendClient()

import grpc
import pandas as pd
import matplotlib.pyplot as plt


def get_top_categories(wiki, start_date, end_date, limit):
    request = topictrend_pb2.TopCategoriesRequest(
        wiki=wiki,
        start_date=start_date,
        end_date=end_date,
        limit=limit
    )

    try:
        response = client.stub.GetTopCategories(request)
        data = []
        for category in response.categories:
          category_name = get_title_by_qid(client, category.category_qid, wiki=wiki) # Pass wiki_lang
          if category_name is None:
            category_name = f"Q{category.category_qid} (Name Not Found)"
          data.append({
            'category_qid': category.category_qid,
            'category_name': category_name,
            'total_views': category.total_views
          })
        return data
    except grpc.RpcError as e:
        print(f"RPC failed: {e.code()}, {e.details()}")


# Fetch top categories for baseline period - September
baseline_categories =  get_top_categories( wiki="kkwiki", start_date="2025-09-01", end_date="2025-09-30", limit=100)

# Fetch top categories for impact period (August)
impact_categories = get_top_categories( wiki="kkwiki", start_date="2025-08-01", end_date="2025-08-31", limit=100)

df_baseline = pd.DataFrame(baseline_categories)
df_impact = pd.DataFrame(impact_categories)

df_baseline.head(10)

df_impact.head(10)

"""# Merge and prepared delta"""

# Rename 'total_views' column to avoid conflict during merge, as 'total_views' is more generic
df_baseline = df_baseline.rename(columns={'total_views': 'pageviews_baseline'})
df_impact = df_impact.rename(columns={'total_views': 'pageviews_impact'})

# Merge on category names
merged = df_baseline.merge(df_impact, on='category_qid', suffixes=('_baseline', '_impact'), how='outer')

# Create a consolidated 'category_name' column, preferring baseline name
merged['category_name'] = merged['category_name_baseline'].fillna(merged['category_name_impact'])

# Fetch missing page views using get_total_page_views_for_category
for index, row in merged.iterrows():
    qid = row['category_qid']
    if pd.isna(row['pageviews_baseline']):
        # Fetch baseline views for this category QID
        baseline_views = get_total_page_views_for_category(client, qid, "kkwiki", "2025-09-01", "2025-09-30")
        merged.loc[index, 'pageviews_baseline'] = baseline_views if baseline_views is not None else 0
    if pd.isna(row['pageviews_impact']):
        # Fetch impact views for this category QID
        impact_views = get_total_page_views_for_category(client,qid, "kkwiki", "2025-08-01", "2025-08-31")
        merged.loc[index, 'pageviews_impact'] = impact_views if impact_views is not None else 0

# Ensure any remaining NaNs (e.g., if get_total_page_views_for_category returned None) are 0
merged['pageviews_baseline'] = merged['pageviews_baseline'].fillna(0)
merged['pageviews_impact'] = merged['pageviews_impact'].fillna(0)

# Calculate percentage change
# Handle division by zero for categories with 0 baseline views
merged['pageview_delta_pct'] = merged.apply(
    lambda row: ((row['pageviews_impact'] - row['pageviews_baseline']) / row['pageviews_baseline'] * 100)
    if row['pageviews_baseline'] != 0 else (100 if row['pageviews_impact'] > 0 else 0),
    axis=1
)

# Sort by impact (most affected first)
merged = merged.sort_values('pageview_delta_pct', ascending=False)

merged_display = merged[['category_qid','category_name', 'pageviews_baseline', 'pageviews_impact', 'pageview_delta_pct']]

merged_display.head(10)

merged_display.tail(10)

"""# Plot the delta

That clearly show Әлеуметтану with 50 times jump is the one we were looking for.
"""

category_qid= merged_display.iloc[0]['category_qid']
category_title= merged_display.iloc[0]['category_name']
request = topictrend_pb2.CategoryViewsRequest(
        wiki="kkwiki",
        category_qid=category_qid,
        start_date="2025-08-01",
        end_date="2025-09-30",
        depth=2
)

try:
    response = client.stub.GetCategoryViews(request)
    print(f"Retrieved {len(response.views)} daily view records")
    for view in response.views[:5]:  # Show first 5 records
        print(f"Date: {view.date}, Views: {view.views}")
    plot_page_views(response.views, f"{category_title} English: {get_title_by_qid(client,category_qid)}")
except grpc.RpcError as e:
    client._handle_grpc_error(e)

plt.figure(figsize=(15, 8))
plt.barh(merged['category_name'][:20], merged['pageview_delta_pct'][:20])
plt.xlabel('Pageview Change (%)')
plt.title('Top 20 Most Increased Categories (kkwiki Aug -> Sept)')
plt.axvline(x=0, color='red', linestyle='--')
plt.tight_layout()

"""Now, let us find which articles in that category got major pageview change"""

def get_top_articles_in_category(client, category_qid, wiki,start_date, end_date, limit=10):
  request = topictrend_pb2.TopArticlesRequest(
    wiki=wiki,
    start_date=start_date,
    end_date=end_date,
    category_qid=category_qid,
    limit=limit,
    depth=20
  )

  try:
    response = client.stub.GetTopArticles(request)

    data = []
    for art in response.articles:
        data.append({
            'article_title': get_title_by_qid(client, art.article_qid),
            'article_title_kk': get_title_by_qid(client, art.article_qid, wiki="kkwiki"),
            'article_qid': art.article_qid,
            'total_views': art.total_views
        })
    return data
  except grpc.RpcError as e:
        print(f"RPC failed: {e.code()}, {e.details()}")

baseline_top_articles = pd.DataFrame(get_top_articles_in_category(client, category_qid, "kkwiki","2025-09-01","2025-09-30"))
impact_top_articles = pd.DataFrame(get_top_articles_in_category(client, category_qid, "kkwiki","2025-08-01","2025-08-30"))

baseline_top_articles

impact_top_articles

"""let us plot the pageviews of first one with"""

article_qid=baseline_top_articles.iloc[0]['article_qid']

request = topictrend_pb2.ArticleViewsRequest(
    wiki="kkwiki",
    article_qid=article_qid,
    start_date="2025-08-01",
    end_date="2025-09-30"
)

try:
    response = client.stub.GetArticleViews(request)
    print(f"Retrieved {len(response.views)} daily view records")
    for view in response.views[:5]:  # Show first 5 records
        print(f"Date: {view.date}, Views: {view.views}")
    plot_page_views(response.views, get_title_by_qid(client, article_qid))
except grpc.RpcError as e:
    client._handle_grpc_error(e)
