[package]
name = "topictrend_cli"
version = "0.1.0"
edition = "2024"
# default-run = "wikigraph"

[[bin]]
name = "wikigraph"
path = "src/main.rs"

[[bin]]
name = "get-categories"
path = "src/categories.rs"

[[bin]]
name = "get-articles"
path = "src/articles.rs"

[[bin]]
name = "get-categorygraph"
path = "src/category_graph.rs"

[[bin]]
name = "get-article_category"
path = "src/article_category.rs"

[[bin]]
name = "get-pageviews"
path = "src/pageviews.rs"

[[bin]]
name = "get-per_day_wiki_stats"
path = "src/per_day_wiki_stats.rs"

[[bin]]
name = "get-day-pageedits"
path = "src/day_pageedits.rs"

[[bin]]
name = "get-gsc-qid-date"
path = "src/google_search_data.rs"

[[bin]]
name = "coverage-matrix"
path = "src/coverage_matrix.rs"

[[bin]]
name = "coverage-overlap"
path = "src/coverage_overlap.rs"

[[bin]]
name = "coverage-articles"
path = "src/coverage_articles.rs"

[dependencies]
topictrend_core = { path = "../topictrend_core" }
parquet = { workspace = true }
parquet_derive = { workspace = true }
polars = { workspace = true }
anyhow = { workspace = true }
ahash = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
rayon = { workspace = true }
byteorder = { workspace = true }
roaring = { workspace = true }

[[bin]]
name = "coverage-gaps"
path = "src/coverage_gaps.rs"
